// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4fIET4k4PaRusPxHeS0pps065TAoxSA4',
    appId: '1:778115499799:web:d9e77efd51dccda552d952',
    messagingSenderId: '778115499799',
    projectId: 'gtlmd-71281',
    authDomain: 'gtlmd-71281.firebaseapp.com',
    databaseURL: 'https://gtlmd-71281-default-rtdb.firebaseio.com',
    storageBucket: 'gtlmd-71281.firebasestorage.app',
    measurementId: 'G-5Y4LC36S5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTdovsT0KQPd1Z2pDrre6xZNUkFSG8dI',
    appId: '1:778115499799:android:23b7dd0c4166973f52d952',
    messagingSenderId: '778115499799',
    projectId: 'gtlmd-71281',
    databaseURL: 'https://gtlmd-71281-default-rtdb.firebaseio.com',
    storageBucket: 'gtlmd-71281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZVNZKNwAce5KlFzyvKqv8Lw1sJAv6eM',
    appId: '1:778115499799:ios:e3a0541be5df195f52d952',
    messagingSenderId: '778115499799',
    projectId: 'gtlmd-71281',
    databaseURL: 'https://gtlmd-71281-default-rtdb.firebaseio.com',
    storageBucket: 'gtlmd-71281.firebasestorage.app',
    iosBundleId: 'com.greensoft.gtlmd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQZVNZKNwAce5KlFzyvKqv8Lw1sJAv6eM',
    appId: '1:778115499799:ios:462774ad6d33de1b52d952',
    messagingSenderId: '778115499799',
    projectId: 'gtlmd-71281',
    databaseURL: 'https://gtlmd-71281-default-rtdb.firebaseio.com',
    storageBucket: 'gtlmd-71281.firebasestorage.app',
    iosBundleId: 'com.example.gtlmd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4fIET4k4PaRusPxHeS0pps065TAoxSA4',
    appId: '1:778115499799:web:e494b179c88f838452d952',
    messagingSenderId: '778115499799',
    projectId: 'gtlmd-71281',
    authDomain: 'gtlmd-71281.firebaseapp.com',
    databaseURL: 'https://gtlmd-71281-default-rtdb.firebaseio.com',
    storageBucket: 'gtlmd-71281.firebasestorage.app',
    measurementId: 'G-SWHSPG7W3N',
  );
}
